[package]
name = "quake-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.12.1"
device_query = "2.1.0"
toml = "0.9.2"
serde = "1.0.219"
serde_derive = "1.0.219"
dirs = "6.0.0"

[build-dependencies]
slint-build = "1.12.1"
